scrape_configs:
  - job_name: 'CashflashMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['cashflash-api:8080']
        labels:
          application: 'Cashflash'

  - job_name: 'postgresql'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
    metrics_path: /metrics
