spring:
  profiles:
    active: default

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/cashflash
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

frontend:
  url: http://localhost:5173
